# Generated by Django 2.2.6 on 2022-04-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.SlugField(unique=True)),
                ('http_url', models.URLField(max_length=255, verbose_name='Сокращаемая ссылка')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('nums_of_visits', models.IntegerField(default=0)),
                ('want_edit', models.BooleanField(default=False)),
            ],
        ),
    ]
